site_name: Meigyoku Wiki
site_description: 我的个人Wiki站点

theme:
  name: material
  logo: asset/favi.jpg # logo 图标
  favicon: asset/favi.jpg # 网页标签图标
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Welcome: index.md
  - Quant:
    - 术语:
      - 夏普比率和偏度:  quant/term/夏普比率和偏度.md

dev_addr: 0.0.0.0:6324

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  # - git-revision-date-localized:
      # type: datetime
plugins:
  - pdf-export:
      media_type: print
      enabled: true
      combined: true           # 将所有页面合并为一个PDF
      cover: true              # 包含封面页
      cover_title: "Meigyoku Wiki"  # 封面标题
      output_path: "site/pdf/meigyoku-wiki.pdf"  # 输出路径