site_name: mizuki7fan site
site_url: https://mizuki7fan.github.io/
site_author: meigyoku
site_description: mizuki7fan site

# Repository
repo_name: mizukifan site
repo_url: https://github.com/Mizuki7fan/Mizuki7fan.github.io

theme:
  name: material
  logo: asset/favi.ico # logo 图标
  favicon: asset/favi.ico # 网页标签图标
  language: zh
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.annotate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Welcome:
    - About: index.md
    - Helloworld: helloworld.md
  - Quant:
    - 术语:
      - 夏普比率和偏度:  quant/term/夏普比率和偏度.md
  - Geometry:
    - Volume Mesh:
      - 综述: geometry/volume mesh/综述.md

dev_addr: 0.0.0.0:6324

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  # - git-revision-date-localized:
      # type: datetime
plugins:
  - pdf-export:
      enabled: false
